"use client";

import { useState } from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Dog, Cat, Home, Download, Loader2, CheckCircle } from "lucide-react";

interface Routine {
  id: number;
  petType: string;
  apartmentSize: string;
  morningRoutine: string;
  afternoonRoutine: string;
  eveningRoutine: string;
  exerciseTips: string;
  feedingSchedule: string;
}

export default function RoutinePage() {
  const [petType, setPetType] = useState<string>("");
  const [apartmentSize, setApartmentSize] = useState<string>("");
  const [routine, setRoutine] = useState<Routine | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  const handleGenerate = async () => {
    if (!petType || !apartmentSize) {
      setError("Please select both pet type and apartment size");
      return;
    }

    setIsLoading(true);
    setError("");

    try {
      const response = await fetch(`/api/routines?pet_type=${petType}&apartment_size=${apartmentSize}`);
      
      if (response.ok) {
        const data = await response.json();
        if (data.id) {
          setRoutine(data);
        } else {
          setError("No routine found for this combination. Please try another selection.");
        }
      } else {
        setError("Failed to fetch routine. Please try again.");
      }
    } catch (err) {
      setError("An error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!routine) return;

    // Create PDF content
    const content = `
PawSpace - Apartment Pet Care Routine
=====================================

Pet Type: ${routine.petType.toUpperCase()}
Apartment Size: ${routine.apartmentSize.toUpperCase()}

MORNING ROUTINE
---------------
${routine.morningRoutine}

AFTERNOON ROUTINE
-----------------
${routine.afternoonRoutine}

EVENING ROUTINE
---------------
${routine.eveningRoutine}

EXERCISE TIPS
-------------
${routine.exerciseTips}

FEEDING SCHEDULE
----------------
${routine.feedingSchedule}

---
Generated by PawSpace - Your Guide to Happy Pets in Small Spaces
Visit: https://pawspace.in
    `;

    // Create and download text file (simulating PDF)
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `pawspace-routine-${routine.petType}-${routine.apartmentSize}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      
      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-gradient-to-br from-[#fef9f3] via-[#fef3e2] to-[#d4f4dd] py-16">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto text-center">
              <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-4">
                Personalized Pet Routine Generator
              </h1>
              <p className="text-lg text-muted-foreground">
                Get a customized daily routine tailored to your pet type and apartment size
              </p>
            </div>
          </div>
        </section>

        {/* Selection Section */}
        <section className="py-12 bg-white">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              <div className="bg-card border border-border rounded-2xl p-8 shadow-lg">
                {/* Pet Type Selection */}
                <div className="mb-8">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Select Your Pet Type</h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <button
                      onClick={() => setPetType("dog")}
                      className={`flex items-center gap-4 p-6 border-2 rounded-xl transition-all ${
                        petType === "dog"
                          ? "border-primary bg-primary/5 shadow-md"
                          : "border-border hover:border-primary/50 hover:bg-secondary"
                      }`}
                    >
                      <div className={`w-12 h-12 rounded-full flex items-center justify-center ${
                        petType === "dog" ? "bg-primary/10" : "bg-secondary"
                      }`}>
                        <Dog className={`w-6 h-6 ${petType === "dog" ? "text-primary" : "text-muted-foreground"}`} />
                      </div>
                      <div className="text-left">
                        <div className="font-semibold text-foreground">Dog</div>
                        <div className="text-sm text-muted-foreground">Active companion</div>
                      </div>
                      {petType === "dog" && (
                        <CheckCircle className="w-5 h-5 text-primary ml-auto" />
                      )}
                    </button>

                    <button
                      onClick={() => setPetType("cat")}
                      className={`flex items-center gap-4 p-6 border-2 rounded-xl transition-all ${
                        petType === "cat"
                          ? "border-primary bg-primary/5 shadow-md"
                          : "border-border hover:border-primary/50 hover:bg-secondary"
                      }`}
                    >
                      <div className={`w-12 h-12 rounded-full flex items-center justify-center ${
                        petType === "cat" ? "bg-primary/10" : "bg-secondary"
                      }`}>
                        <Cat className={`w-6 h-6 ${petType === "cat" ? "text-primary" : "text-muted-foreground"}`} />
                      </div>
                      <div className="text-left">
                        <div className="font-semibold text-foreground">Cat</div>
                        <div className="text-sm text-muted-foreground">Independent friend</div>
                      </div>
                      {petType === "cat" && (
                        <CheckCircle className="w-5 h-5 text-primary ml-auto" />
                      )}
                    </button>
                  </div>
                </div>

                {/* Apartment Size Selection */}
                <div className="mb-8">
                  <h3 className="text-xl font-semibold text-foreground mb-4">Select Your Apartment Size</h3>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                    {[
                      { value: "studio", label: "Studio", subtitle: "250-350 sq ft" },
                      { value: "1bhk", label: "1 BHK", subtitle: "400-600 sq ft" },
                      { value: "2bhk", label: "2 BHK", subtitle: "700-1000 sq ft" },
                      { value: "3bhk", label: "3 BHK", subtitle: "1000+ sq ft" },
                    ].map((size) => (
                      <button
                        key={size.value}
                        onClick={() => setApartmentSize(size.value)}
                        className={`flex flex-col items-center gap-3 p-6 border-2 rounded-xl transition-all ${
                          apartmentSize === size.value
                            ? "border-primary bg-primary/5 shadow-md"
                            : "border-border hover:border-primary/50 hover:bg-secondary"
                        }`}
                      >
                        <div className={`w-12 h-12 rounded-full flex items-center justify-center ${
                          apartmentSize === size.value ? "bg-primary/10" : "bg-secondary"
                        }`}>
                          <Home className={`w-6 h-6 ${apartmentSize === size.value ? "text-primary" : "text-muted-foreground"}`} />
                        </div>
                        <div className="text-center">
                          <div className="font-semibold text-foreground">{size.label}</div>
                          <div className="text-xs text-muted-foreground">{size.subtitle}</div>
                        </div>
                        {apartmentSize === size.value && (
                          <CheckCircle className="w-5 h-5 text-primary" />
                        )}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Error Message */}
                {error && (
                  <div className="mb-6 p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive text-sm">
                    {error}
                  </div>
                )}

                {/* Generate Button */}
                <button
                  onClick={handleGenerate}
                  disabled={isLoading || !petType || !apartmentSize}
                  className="w-full bg-primary hover:bg-primary/90 text-primary-foreground font-semibold py-4 px-6 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Generating Your Routine...
                    </>
                  ) : (
                    "Generate Personalized Routine"
                  )}
                </button>
              </div>
            </div>
          </div>
        </section>

        {/* Routine Display Section */}
        {routine && (
          <section className="py-12 bg-secondary">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
              <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="flex items-center justify-between mb-8">
                  <h2 className="text-3xl font-bold text-foreground">
                    Your Personalized Routine
                  </h2>
                  <button
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors font-medium"
                  >
                    <Download className="w-5 h-5" />
                    Download PDF
                  </button>
                </div>

                {/* Routine Cards */}
                <div className="space-y-6">
                  {/* Morning Routine */}
                  <div className="bg-white rounded-xl p-6 shadow-md">
                    <h3 className="text-xl font-semibold text-foreground mb-4">🌅 Morning Routine</h3>
                    <p className="text-muted-foreground whitespace-pre-line">{routine.morningRoutine}</p>
                  </div>

                  {/* Afternoon Routine */}
                  <div className="bg-white rounded-xl p-6 shadow-md">
                    <h3 className="text-xl font-semibold text-foreground mb-4">☀️ Afternoon Routine</h3>
                    <p className="text-muted-foreground whitespace-pre-line">{routine.afternoonRoutine}</p>
                  </div>

                  {/* Evening Routine */}
                  <div className="bg-white rounded-xl p-6 shadow-md">
                    <h3 className="text-xl font-semibold text-foreground mb-4">🌙 Evening Routine</h3>
                    <p className="text-muted-foreground whitespace-pre-line">{routine.eveningRoutine}</p>
                  </div>

                  {/* Exercise Tips */}
                  <div className="bg-white rounded-xl p-6 shadow-md">
                    <h3 className="text-xl font-semibold text-foreground mb-4">💪 Exercise Tips</h3>
                    <p className="text-muted-foreground whitespace-pre-line">{routine.exerciseTips}</p>
                  </div>

                  {/* Feeding Schedule */}
                  <div className="bg-white rounded-xl p-6 shadow-md">
                    <h3 className="text-xl font-semibold text-foreground mb-4">🍽️ Feeding Schedule</h3>
                    <p className="text-muted-foreground whitespace-pre-line">{routine.feedingSchedule}</p>
                  </div>
                </div>

                {/* CTA */}
                <div className="mt-8 p-6 bg-primary/5 border border-primary/20 rounded-xl text-center">
                  <p className="text-foreground mb-4">
                    Want more personalized advice and premium guides?
                  </p>
                  <a
                    href="/membership"
                    className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors font-medium"
                  >
                    Explore Membership Benefits
                  </a>
                </div>
              </div>
            </div>
          </section>
        )}
      </main>
      
      <Footer />
    </div>
  );
}
