import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Food Products (5)
        {
            name: 'Premium Grain-Free Dog Food 30lb',
            description: 'High-protein formula perfect for apartment dogs with limited exercise space. Natural ingredients support healthy weight management and reduce waste output for easy cleanup.',
            price: '$49.99',
            affiliateLink: 'https://amazon.com/product-slug-1',
            imageUrl: '/images/products/product-1.jpg',
            category: 'food',
            petType: 'dog',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Small Breed Indoor Dog Food 15lb',
            description: 'Specially formulated for small dogs living in apartments. Smaller kibble size and balanced nutrition help maintain ideal weight without excessive portions.',
            price: '$34.99',
            affiliateLink: 'https://amazon.com/product-slug-2',
            imageUrl: '/images/products/product-2.jpg',
            category: 'food',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Indoor Cat Formula Dry Food 12lb',
            description: 'Designed for indoor cats with reduced calorie content to prevent obesity. Special fiber blend controls hairballs and promotes healthy digestion in limited-space living.',
            price: '$39.99',
            affiliateLink: 'https://amazon.com/product-slug-3',
            imageUrl: '/images/products/product-3.jpg',
            category: 'food',
            petType: 'cat',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Sensitive Stomach Cat Food 10lb',
            description: 'Gentle formula for cats prone to digestive issues in apartment settings. Easy-to-digest proteins and prebiotics minimize litter box odors and accidents.',
            price: '$42.99',
            affiliateLink: 'https://amazon.com/product-slug-4',
            imageUrl: '/images/products/product-4.jpg',
            category: 'food',
            petType: 'cat',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Multi-Pet Household Food Variety Pack',
            description: 'Convenient variety pack for homes with both dogs and cats. Individual portion pouches save storage space and keep food fresh longer in small apartments.',
            price: '$44.99',
            affiliateLink: 'https://amazon.com/product-slug-5',
            imageUrl: '/images/products/product-5.jpg',
            category: 'food',
            petType: 'both',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-01-25').toISOString(),
        },

        // Toys (5)
        {
            name: 'Quiet Squeaker Dog Toy Set',
            description: 'Noise-friendly toys perfect for apartment living with thin walls. Soft squeakers provide engagement without disturbing neighbors during playtime.',
            price: '$19.99',
            affiliateLink: 'https://amazon.com/product-slug-6',
            imageUrl: '/images/products/product-6.jpg',
            category: 'toys',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Indoor Fetch Ball Launcher',
            description: 'Compact automatic ball launcher for small spaces. Adjustable distance settings let your dog exercise indoors without disturbing neighbors or breaking valuables.',
            price: '$45.99',
            affiliateLink: 'https://amazon.com/product-slug-7',
            imageUrl: '/images/products/product-7.jpg',
            category: 'toys',
            petType: 'dog',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Interactive Puzzle Feeder for Cats',
            description: 'Mental stimulation toy that keeps indoor cats entertained for hours. Slow-feeding design prevents overeating while providing enrichment in limited space.',
            price: '$24.99',
            affiliateLink: 'https://amazon.com/product-slug-8',
            imageUrl: '/images/products/product-8.jpg',
            category: 'toys',
            petType: 'cat',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Wall-Mounted Cat Play Station',
            description: 'Space-saving vertical play system maximizes apartment walls. Includes toys, scratching surfaces, and perches without taking up valuable floor space.',
            price: '$64.99',
            affiliateLink: 'https://amazon.com/product-slug-9',
            imageUrl: '/images/products/product-9.jpg',
            category: 'toys',
            petType: 'cat',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Smart Motion-Activated Laser Toy',
            description: 'Automatic laser toy keeps pets entertained while you work from home. Silent operation and adjustable patterns work for both cats and small dogs.',
            price: '$32.99',
            affiliateLink: 'https://amazon.com/product-slug-10',
            imageUrl: '/images/products/product-10.jpg',
            category: 'toys',
            petType: 'both',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-08').toISOString(),
        },

        // Grooming Products (5)
        {
            name: 'Quiet Cordless Pet Clipper Set',
            description: 'Ultra-quiet grooming clippers designed for apartment use. Low-noise motor keeps pets calm and prevents neighbor disturbances during grooming sessions.',
            price: '$54.99',
            affiliateLink: 'https://amazon.com/product-slug-11',
            imageUrl: '/images/products/product-11.jpg',
            category: 'grooming',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Portable Dog Bathing Station',
            description: 'Compact folding tub perfect for apartment bathrooms. Includes sprayer attachment and drainage system to make bath time easier in small spaces.',
            price: '$69.99',
            affiliateLink: 'https://amazon.com/product-slug-12',
            imageUrl: '/images/products/product-12.jpg',
            category: 'grooming',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Self-Cleaning Cat Grooming Arch',
            description: 'Space-saving grooming station that cats use independently. Collects loose fur in hidden compartment, reducing shedding around your apartment.',
            price: '$28.99',
            affiliateLink: 'https://amazon.com/product-slug-13',
            imageUrl: '/images/products/product-13.jpg',
            category: 'grooming',
            petType: 'cat',
            featured: false,
            rating: 5,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Waterless Cat Shampoo Foam',
            description: 'No-rinse grooming solution perfect for apartments without bathtub access. Quick-dry formula keeps cats clean without the stress of traditional bathing.',
            price: '$16.99',
            affiliateLink: 'https://amazon.com/product-slug-14',
            imageUrl: '/images/products/product-14.jpg',
            category: 'grooming',
            petType: 'cat',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-17').toISOString(),
        },
        {
            name: 'Self-Cleaning Slicker Brush',
            description: 'One-button fur removal makes grooming cleanup effortless in small spaces. Works equally well on both dog and cat coats for multi-pet households.',
            price: '$29.99',
            affiliateLink: 'https://amazon.com/product-slug-15',
            imageUrl: '/images/products/product-15.jpg',
            category: 'grooming',
            petType: 'both',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-02-20').toISOString(),
        },

        // Bedding Products (5)
        {
            name: 'Memory Foam Orthopedic Dog Bed',
            description: 'Premium comfort bed with washable cover perfect for apartment living. Non-slip base and neutral design complement any decor while providing joint support.',
            price: '$79.99',
            affiliateLink: 'https://amazon.com/product-slug-16',
            imageUrl: '/images/products/product-16.jpg',
            category: 'bedding',
            petType: 'dog',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Compact Elevated Dog Bed',
            description: 'Space-saving raised bed keeps floors clear and improves air circulation. Lightweight and foldable design perfect for small apartments with limited storage.',
            price: '$44.99',
            affiliateLink: 'https://amazon.com/product-slug-17',
            imageUrl: '/images/products/product-17.jpg',
            category: 'bedding',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Window Perch Cat Bed',
            description: 'Maximizes vertical space by utilizing windows for cat lounging. Sturdy suction cups hold up to 50lbs while giving cats entertainment without floor clutter.',
            price: '$38.99',
            affiliateLink: 'https://amazon.com/product-slug-18',
            imageUrl: '/images/products/product-18.jpg',
            category: 'bedding',
            petType: 'cat',
            featured: true,
            rating: 5,
            createdAt: new Date('2024-02-27').toISOString(),
        },
        {
            name: 'Heated Cat Cave Bed',
            description: 'Energy-efficient self-warming bed perfect for apartments with inconsistent heating. Collapsible design stores easily when not in use during warmer months.',
            price: '$42.99',
            affiliateLink: 'https://amazon.com/product-slug-19',
            imageUrl: '/images/products/product-19.jpg',
            category: 'bedding',
            petType: 'cat',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Multi-Pet Cushion Bed Large',
            description: 'Versatile bed suitable for both dogs and cats in multi-pet homes. Machine-washable microfiber cover and low-profile design fits seamlessly in any room.',
            price: '$56.99',
            affiliateLink: 'https://amazon.com/product-slug-20',
            imageUrl: '/images/products/product-20.jpg',
            category: 'bedding',
            petType: 'both',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-03').toISOString(),
        },

        // Training Products (3)
        {
            name: 'Clicker Training Kit with Guide',
            description: 'Complete training system perfect for teaching quiet apartment behavior. Includes wrist strap clicker and illustrated guide for positive reinforcement techniques.',
            price: '$15.99',
            affiliateLink: 'https://amazon.com/product-slug-21',
            imageUrl: '/images/products/product-21.jpg',
            category: 'training',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Indoor Potty Training Pad System',
            description: 'Apartment-friendly potty solution with odor-eliminating technology. Reusable washable pads and holder tray keep your space clean during training.',
            price: '$34.99',
            affiliateLink: 'https://amazon.com/product-slug-22',
            imageUrl: '/images/products/product-22.jpg',
            category: 'training',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Bark Control Training Collar',
            description: 'Neighbor-friendly solution using vibration and sound to discourage excessive barking. Adjustable sensitivity levels ensure humane training in close quarters.',
            price: '$48.99',
            affiliateLink: 'https://amazon.com/product-slug-23',
            imageUrl: '/images/products/product-23.jpg',
            category: 'training',
            petType: 'dog',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-10').toISOString(),
        },

        // Health Products (2)
        {
            name: 'Joint Support Supplement for Dogs',
            description: 'Essential supplement for apartment dogs with limited outdoor exercise. Supports hip and joint health to prevent issues common in less active indoor pets.',
            price: '$32.99',
            affiliateLink: 'https://amazon.com/product-slug-24',
            imageUrl: '/images/products/product-24.jpg',
            category: 'health',
            petType: 'dog',
            featured: false,
            rating: 5,
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            name: 'Hairball Control Supplement for Cats',
            description: 'Reduces hairball formation in indoor cats who groom more frequently. Natural fiber formula promotes digestive health and minimizes apartment cleanup.',
            price: '$24.99',
            affiliateLink: 'https://amazon.com/product-slug-25',
            imageUrl: '/images/products/product-25.jpg',
            category: 'health',
            petType: 'cat',
            featured: false,
            rating: 4,
            createdAt: new Date('2024-03-15').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});